In [13]:
from tqdm import tqdm
import pandas as po
import numpy as np

In [28]:
df = po.read_pickle('../DataAnalysis_v2/eDTWBI_Imputed_Data.pkl')
df

consumption
time                              
2017-01-01 00:00:00  126661.288667
2017-01-01 00:15:00  125975.630600
2017-01-01 00:30:00  131628.821400
2017-01-01 00:45:00  133741.109667
2017-01-01 01:00:00  149806.386667
...                            ...
2019-11-04 22:45:00  103932.504002
2019-11-04 23:00:00  102064.379714
2019-11-04 23:15:00  100378.796042
2019-11-04 23:30:00   98593.460339
2019-11-04 23:45:00   97365.874939

[99648 rows x 1 columns]

In [29]:
df['Date'] = df.index.date
df['Time'] = df.index.time

In [30]:
df

consumption        Date      Time
time                                                    
2017-01-01 00:00:00  126661.288667  2017-01-01  00:00:00
2017-01-01 00:15:00  125975.630600  2017-01-01  00:15:00
2017-01-01 00:30:00  131628.821400  2017-01-01  00:30:00
2017-01-01 00:45:00  133741.109667  2017-01-01  00:45:00
2017-01-01 01:00:00  149806.386667  2017-01-01  01:00:00
...                            ...         ...       ...
2019-11-04 22:45:00  103932.504002  2019-11-04  22:45:00
2019-11-04 23:00:00  102064.379714  2019-11-04  23:00:00
2019-11-04 23:15:00  100378.796042  2019-11-04  23:15:00
2019-11-04 23:30:00   98593.460339  2019-11-04  23:30:00
2019-11-04 23:45:00   97365.874939  2019-11-04  23:45:00

[99648 rows x 3 columns]

In [31]:
df['Year'] = df['Date'].apply(lambda x: x.year)
df['Month'] = df['Date'].apply(lambda x: x.month)

In [32]:
df['DayOfYear'] = df['Date'].apply(lambda x: x.timetuple().tm_yday)
df['DayOfWeek'] = df['Date'].apply(lambda x: x.weekday())
df['DayType']   = df['DayOfWeek'].apply(lambda x: 1 if x < 5 else 0)

In [33]:
df['Hour'] = df['Time'].apply(lambda x: x.hour)
df['Minute'] = df['Time'].apply(lambda x: x.minute)

In [34]:
seasons = {'Winter': [10, 11, 12, 1, 2], 'Summer': [3, 4, 5, 6], 'Monsoon': [7, 8, 9]}

In [35]:
m2s = [-1, 0, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0]

In [36]:
len(m2s)

13

In [37]:
df['Season'] = df['Month'].apply(lambda x: m2s[x])

In [38]:
df['Year'] = df['Date'].apply(lambda x: x.year)

In [39]:
df = df.drop(['Time', 'Date'], axis=1)

In [40]:
df

consumption  Year  Month  DayOfYear  DayOfWeek  \
time                                                                    
2017-01-01 00:00:00  126661.288667  2017      1          1          6   
2017-01-01 00:15:00  125975.630600  2017      1          1          6   
2017-01-01 00:30:00  131628.821400  2017      1          1          6   
2017-01-01 00:45:00  133741.109667  2017      1          1          6   
2017-01-01 01:00:00  149806.386667  2017      1          1          6   
...                            ...   ...    ...        ...        ...   
2019-11-04 22:45:00  103932.504002  2019     11        308          0   
2019-11-04 23:00:00  102064.379714  2019     11        308          0   
2019-11-04 23:15:00  100378.796042  2019     11        308          0   
2019-11-04 23:30:00   98593.460339  2019     11        308          0   
2019-11-04 23:45:00   97365.874939  2019     11        308          0   

                     DayType  Hour  Minute  Season  
time                                                
2017-01-01 00:00:00        0     0       0       0  
2017-01-01 00:15:00        0     0      15       0  
2017-01-01 00:30:00        0     0      30       0  
2017-01-01 00:45:00        0     0      45       0  
2017-01-01 01:00:00        0     1       0       0  
...                      ...   ...     ...     ...  
2019-11-04 22:45:00        1    22      45       0  
2019-11-04 23:00:00        1    23       0       0  
2019-11-04 23:15:00        1    23      15       0  
2019-11-04 23:30:00        1    23      30       0  
2019-11-04 23:45:00        1    23      45       0  

[99648 rows x 9 columns]

In [41]:
df.to_csv('multivariate.csv', index=False)

In [60]:
df = po.read_csv('multivariate.csv')
df

consumption  Year  Month  DayOfYear  DayOfWeek  DayType  Hour  \
0      126661.288667  2017      1          1          6        0     0   
1      125975.630600  2017      1          1          6        0     0   
2      131628.821400  2017      1          1          6        0     0   
3      133741.109667  2017      1          1          6        0     0   
4      149806.386667  2017      1          1          6        0     1   
...              ...   ...    ...        ...        ...      ...   ...   
99643  103932.504002  2019     11        308          0        1    22   
99644  102064.379714  2019     11        308          0        1    23   
99645  100378.796042  2019     11        308          0        1    23   
99646   98593.460339  2019     11        308          0        1    23   
99647   97365.874939  2019     11        308          0        1    23   

       Minute  Season  
0           0       0  
1          15       0  
2          30       0  
3          45       0  
4           0       0  
...       ...     ...  
99643      45       0  
99644       0       0  
99645      15       0  
99646      30       0  
99647      45       0  

[99648 rows x 9 columns]

In [61]:
def make_windows(data, train_seq_len = 4*24*7, val_seq_len = 4*24):
    X = np.zeros((len(data) - val_seq_len + 1 - train_seq_len, train_seq_len, len(data.columns)))
    y = np.zeros((len(data) - val_seq_len + 1 - train_seq_len, val_seq_len, 1))

    for i in tqdm(range(train_seq_len, len(data) - val_seq_len + 1)):        
        X[i-train_seq_len, :, :] = data.values[i - train_seq_len: i]
        y[i-train_seq_len, :, :] = data['consumption'].values[i: i + val_seq_len].reshape(-1, 1)
        
    return X, y

In [62]:
X, y = make_windows(df)

100%|██████████| 98881/98881 [01:16<00:00, 1286.98it/s]


In [63]:
X.shape

(98881, 672, 9)

In [64]:
y.shape

(98881, 96, 1)

In [3]:
train_seq_len = 4*24*7
val_seq_len = 4*24
data = df

In [25]:
X = np.zeros((len(data) - val_seq_len + 1 - train_seq_len, train_seq_len, len(data.columns)))
y = np.zeros((len(data) - val_seq_len + 1 - train_seq_len, val_seq_len, 1))

In [40]:
for i in tqdm(range(train_seq_len, len(data) - val_seq_len + 1)):        
    X[i-train_seq_len, :, :] = data.values[i - train_seq_len: i]
    y[i-train_seq_len, :, :] = data['consumption'].values[i: i + val_seq_len].reshape(-1, 1)

100%|██████████| 98881/98881 [01:14<00:00, 1325.13it/s]


In [57]:
df.iloc[train_seq_len-10:train_seq_len+10]

consumption  Year  Month  DayOfYear  DayOfWeek  DayType  Hour  Minute  \
662  85175.797667  2017      1          7          5        0    21      30   
663  83750.254000  2017      1          7          5        0    21      45   
664  84045.454200  2017      1          7          5        0    22       0   
665  81897.511733  2017      1          7          5        0    22      15   
666  80842.488400  2017      1          7          5        0    22      30   
667  82252.116267  2017      1          7          5        0    22      45   
668  81108.183400  2017      1          7          5        0    23       0   
669  82448.346733  2017      1          7          5        0    23      15   
670  83156.285941  2017      1          7          5        0    23      30   
671  82049.840000  2017      1          7          5        0    23      45   
672  81958.566429  2017      1          8          6        0     0       0   
673  81703.568000  2017      1          8          6        0     0      15   
674  81155.458267  2017      1          8          6        0     0      30   
675  77713.644733  2017      1          8          6        0     0      45   
676  75768.328643  2017      1          8          6        0     1       0   
677  50288.613500  2017      1          8          6        0     1      15   
678  51770.267500  2017      1          8          6        0     1      30   
679  51050.958467  2017      1          8          6        0     1      45   
680  51088.090467  2017      1          8          6        0     2       0   
681  53280.426067  2017      1          8          6        0     2      15   

     Season  
662       0  
663       0  
664       0  
665       0  
666       0  
667       0  
668       0  
669       0  
670       0  
671       0  
672       0  
673       0  
674       0  
675       0  
676       0  
677       0  
678       0  
679       0  
680       0  
681       0

In [59]:
X[0, :, 6][-10:]

array([21., 21., 22., 22., 22., 22., 23., 23., 23., 23.])

In [58]:
X[0, :, 1][-10:]

array([2017., 2017., 2017., 2017., 2017., 2017., 2017., 2017., 2017.,
       2017.])

In [53]:
y[0, :, 0][:10]

array([81958.56642857, 81703.568     , 81155.45826667, 77713.64473333,
       75768.32864286, 50288.6135    , 51770.2675    , 51050.95846667,
       51088.09046667, 53280.42606667])

In [56]:
y[0, :, 0][:10]

array([81958.56642857, 81703.568     , 81155.45826667, 77713.64473333,
       75768.32864286, 50288.6135    , 51770.2675    , 51050.95846667,
       51088.09046667, 53280.42606667])